pull_request_rules:
  - name: automatic merge (with squash) with strict when reviewed and not work in progress
    conditions:
      - '#approved-reviews-by>=0'
      - '#review-requested=0'
      - '#changes-requested-reviews-by=0'
      #- '#commented-reviews-by=0'
      - label != "work in progress"
      - label = "okay to merge"
      - label != "don't squash"
      #- status-success=Commit Message Lint
      #- milestone ~= '^maistra-\d+-\d+$'
    actions:
      merge:
        method: squash
        strict: smart
  - name: automatic merge (without squash) with strict when reviewed and not work in progress
    conditions:
      - '#approved-reviews-by>=0'
      - '#review-requested=0'
      - '#changes-requested-reviews-by=0'
      #- '#commented-reviews-by=0'
      - label != "work in progress"
      - label = "okay to merge"
      - label = "don't squash"
      #- status-success=Commit Message Lint
      #- milestone ~= '^maistra-\d+-\d+$'
    actions:
      merge:
        method: rebase
        strict: smart
  - name: label work in progress PRs
    conditions:
      - label != "work in progress"
      - title ~= '^WIP\b'
    actions:
      label:
        add:
          - "work in progress"
  - name: remove work in progress labels
    conditions:
      - label = "work in progress"
      - title ~= '^(?!WIP\b)'
    actions:
      label:
        remove:
          - "work in progress"
  - name: label PRs needing review
    conditions:
    - label != "needs review"
    - label != "work in progress"
    - '#approved-reviews-by<2'
    - '#changes-requested-reviews-by=0'
    actions:
      label:
        add:
        - "needs review"
  - name: remove needs-review label when in progress
    conditions:
    - label = "needs review"
    - label = "work in progress"
    actions:
      label:
        remove:
        - "needs review"
  - name: remove needs-review label when approved by two people
    conditions:
    - label = "needs review"
    - '#approved-reviews-by>=2'
    actions:
      label:
        remove:
        - "needs review"
  - name: remove needs-review label when changes requested
    conditions:
    - label = "needs review"
    - '#changes-requested-reviews-by>0'
    actions:
      label:
        remove:
        - "needs review"
  - name: label ready-to-merge
    conditions:
      - label != "work in progress"
      - label != "needs review"
    actions:
      label:
        add:
        - "ready to merge"
  - name: remove ready-to-merge label when WIP
    conditions:
      - label = "work in progress"
    actions:
      label:
        remove:
        - "ready to merge"
  - name: remove ready-to-merge label when review needed
    conditions:
      - label = "needs review"
    actions:
      label:
        remove:
        - "ready to merge"
